### ISSUE TITLE
Having some trouble to create a schema based on a complicated XSD file

### ISSUE THREAD

**Issue by jping0929** [brunato/xmlschema#44]
Hi there,

I am trying to use this tool to import some xsd files from this [repository](https://github.com/DIGGSml/diggs-schema/tree/2.5.a-dev.)

The specific schema I am looking into is called [Kernel.xsd,](https://github.com/DIGGSml/diggs-schema/blob/2.5.a-dev/Kernel.xsd) and it begins with:
```XML
<?xml version="1.0" encoding="utf-8"?>
<schema xmlns:diggs="http://diggsml.org/schemas/2.5.a"
    xmlns:diggs_geo="http://diggsml.org/schemas/2.5.a/geotechnical"
    xmlns:g3.3="http://www.opengis.net/gml/3.3/ce" xmlns:glr="http://www.opengis.net/gml/3.3/lr"
    xmlns:glrov="http://www.opengis.net/gml/3.3/lrov"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.w3.org/2001/XMLSchema"
    xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:witsml="http://www.witsml.org/schemas/131"
    xmlns:gml="http://www.opengis.net/gml/3.2"
    xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning"
    targetNamespace="http://diggsml.org/schemas/2.5.a" version="2.5.a"
    elementFormDefault="qualified" vc:maxVersion="1.1" vc:minVersion="1.0">
    <!--
 import the gml and xlinks namespaces (original local profiles)  
-->
    <import namespace="http://www.opengis.net/gml/3.2" schemaLocation="gml3.2Profile_diggs.xsd"/>
    <import namespace="http://www.opengis.net/gml/3.3/ce" schemaLocation="gml3.3Profile_diggs.xsd"/>
    <import namespace="http://www.opengis.net/gml/3.3/lr" schemaLocation="glrProfile_diggs.xsd"/>
    <import namespace="http://www.opengis.net/gml/3.3/lrov" schemaLocation="glrovProfile_diggs.xsd"/>
    <import namespace="http://www.w3.org/1999/xlink" schemaLocation="xlinks.xsd"/>
    <import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="xml.xsd"/>
```
I am having some trouble using `xmlschema.XMLSchema` to create it as Kernel.xsl have references to other schema, but I could not find documentations to use `xmlschema.XMLSchema` properly for such files.

Thanks

**Comment by brunato** [comment]
I tried these schemas. The main problem is an inclusion of a new proposed version of the XLink schema, that is a base schema needed for building the meta schema. The new version of this schema includes different attribute groups and this cause incompatibility with the old definitions.

Importing schemas is not simple and schema processors usually avoid imports of already imported namespaces. In the new version 0.9.21 I've put a workaround for your problem:

```python
>>> import xmlschema
>>> xlink_schema = xmlschema.XMLSchema('xlinks.xsd')  # Change XLink base schema
>>> kernel_schema = xmlschema.XMLSchema('Kernel.xsd', global_maps=xlink_schema.maps)  # Use the new maps
```
This workaround has success because in the new version I've implemented meta-schema rebuilding when I use a schema of one of the base schema namespaces.
I will try to improve schema importing (maybe forcing with a parameter).

**Comment by jping0929** [comment]
Thanks for you help. This really helped me a lot.

**Comment by brunato** [comment]
Closing the issue, considering this limitation overseeded by v1.0+ of the package. 
Warning messages are now displayed for failed includes or imports and all schema location hints are retrieved from XML source data. For similar problems it's better to open a new specific issue.
