### ISSUE TITLE
Generate xml from xsd schema

### ISSUE THREAD

**Issue by camux** [brunato/xmlschema#47]
Hi, 

It's possible create new xml file from xsd schema, passing dict data?

Example in pseudocode

my_schema = xmlschema.XMLSchema('xmlschema/tests/cases/examples/vehicles/vehicles.xsd')
data = {
   'car1': 'fine',
   'car2': 'bad'
}

new_xml = my_schema.create_xml(data)   # name method is example

print(new_xml)  # New generated xml file

Thanks for advance

**Comment by brunato** [comment]
I'll intended to implement encoding from data to xml (see `iter_encode()` in the code), using the schema as decoder and validator, but at this moment this is incomplete and not supported (as is written in docs), because I want to consolidate the decoding process first.

I'll label this as _enhancement_ and leave open until the feature will be implemented.

Best Regards
Davide

**Comment by ski7777** [comment]
Any updates to this?
It would be really nice for my project. Maybe I will try to implement it

**Comment by brunato** [comment]
Data encoding from object to XML is now implemented from version v1.0+ (1.0.1+ from pip). 

There are some limitations for a bug that has to be fixed in `XsdGroup.iter_group()` that does not permit to realize a strict validatated encoding (using a losslessly converter). So, still some work is needed for this.

**Comment by brunato** [comment]
A first version of strict validation of encoding (from data to XML) has been implemented in version 1.0.3. The same method will be refined and probably then it will used also for decoding in a future version of the library.

**Comment by brunato** [comment]
The method for strict validation of encoding is now complete. It's based on a model visitor class (*XsdModelVisitor* in module *groups.py*) and is now the method used also for decoding. It replaces the old method for decoding that was based on recursion of iter_decode_children(), remove from the code.

So I close this ticket now. Open a new one for specific issues on encoding.
