### ISSUE TITLE
How do I use XsdGlobals?

### ISSUE THREAD

**Issue by virtuald** [brunato/xmlschema#60]
Previously, I could get the XsdType for things like string/boolean/decimal from XSD_BUILTIN_TYPES ... but they seem to have been buried somewhere. I figure they're in XsdGlobals somehow... but when I try to build it:

```
import xmlschema
g = xmlschema.XsdGlobals(xmlschema.XMLSchema_1_0)
g.build()
```
I get an exception stating `'http://www.w3.org/2001/XMLSchema' namespace is not registered.`

What's the right way to get the base types? Thanks!

**Comment by brunato** [comment]
The base types are defined within the meta_schema, that is a part of XMLSchema class:

```python
>>> import xmlschema
>>> xmlschema.XMLSchema.meta_schema.maps.types['{http://www.w3.org/2001/XMLSchema}string']
XsdAtomicBuiltin(name='xs:string')
```

XsdGlobal is the class of `maps` schema attributes and is essentially a mediator to chain distinct included/imported schemas with the starting schema. It could be passed to schema init in complex cases of resource loading, but usually it doesn't has practical usage and generally are created copying the map of the meta_schema, so avoiding built-in types rebuilding.

I've not thought yet howto provide the access to built-in types at module level (maybe a copy of the meta_schema maps). Suggestions are welcome.

**Comment by virtuald** [comment]
I think that's exactly what I need, thanks!

**Comment by stimon** [comment]
Sorry for reviving this but I'm bumping into kind of the same issue. 
I'm trying to use XsdGlobals so I can decode big XML files that carry elements defined in quite a few different schemas (not 100% sure if this is the way of doing it).
```python
self._xnat_base = xmlschema.XMLSchema(locations['http://nrg.wustl.edu/xnat'])
self._globals = xmlschema.XsdGlobals(self._xnat_base, validation='lax')
for ns, location in self.schema_locations.items():
    schema = xmlschema.XMLSchema(location, validation='lax')
    self._globals.register(schema)

self._globals.build()
```
And build throws the `'http://www.w3.org/2001/XMLSchema' namespace is not registered.` Precisely at line 358, in build
```python
meta_schema = self.namespaces[XSD_NAMESPACE][0]
```

**Comment by brunato** [comment]
Hi,

usually you don't need to create an `XsdGlobal` instance, because is the schema instance that automatically creates the global maps if those are not passed as argument. 

For composite schemas the XSD standard provides *xs:include* an *xs:import* to add automatically additional definitions/declarations from the same namespace (include) or from other namespaces (import). My advice is to add the missing include and import statements if you can modify the base schema.

With this package also a manual include/import can be done using `include_schema()` and `import_namespace()` methods of the `XMLSchema` class. With this procedure you can try to start with creating the base schema without building the maps and the import the missing namespace, as in this example:

```python
xs = xmlschema.XMLSchema(<schema location>, build=False)
xs.import_namespace(<other-namespace>, <other schema location>)
xs.build()
```
Remember that namespace imports are done once per namespace, or you need to force. Using `XsdGlobals` register is an option but can be error prone (it doesn't set automatically all the includes and import references also set in schemas) so I discourage to use this way.

Davide

**Comment by stimon** [comment]
This works like a charm, thanks! 
It will save me a lot of time :)
