### ISSUE TITLE
XMLSchemaKeyError on valid xml files

### ISSUE THREAD

**Issue by saschnet** [brunato/xmlschema#82]
With the current xmlschema-1.0.3 I ran into this issue on a xml file (attached below) which is successfully validated at several other validation services:

`import xmlschema`
`xmlschema.validate('fuelPriceExample_v01-01-00.xml', 'PetrolStationPublication_v01-01-00.xsd')`
`XMLSchemaKeyError: "missing a XsdSimpleType or XsdComplexType object for 'FuelPricePublication'!"`

The same error persists using the other functions like is_valid() or to_dict().

[fuelPriceExample_v01-01-00.zip](https://github.com/brunato/xmlschema/files/2408213/fuelPriceExample_v01-01-00.zip)

**Comment by brunato** [comment]
It's an error related to the default namespace mapping for the value of the `xsi:type` attribute. The error is the same because it's generated by the common inner method *iter_decode*.

Also I forgot to insert a protection for `lookup_type` call, then a *KeyError* is raised instead of a validaton error. Probably I'll make an hotfix release for this and other lookup related issues ASAP.

Thank you for reporting it.

**Comment by saschnet** [comment]
Thank you for your help and for maintaining this important library!

I am looking forward to use it after the hotfix release is published.

**Comment by brunato** [comment]
Hi, the hotfix v1.0.5 is released. Try it with your data and report for further errors or close this issue.
Thanks
