### ISSUE TITLE
regex translation issue: validation of particular regex does not raise XMLSchemaValidationError

### ISSUE THREAD

**Issue by r2dan** [brunato/xmlschema#83]
Hi,

I've some issues with validation against the following XSD Schema element:
```
  <xs:simpleType name="config">
    <xs:restriction base="xs:string">
      <xs:whiteSpace value="collapse"/>
      <xs:pattern value="(word|other)|(alternative)"/>
    </xs:restriction>
  </xs:simpleType>
```

It does not raise an exception when setting the config field to `word foo` and on `foo alternative`. 

I think this is due to how you handle regex conversation between xsd and how Python handles it. In my particular case it would help to change the conversion algorithm to make something like this as the outcome of conversion: `(^word|other$)|(^alternative$)`. It would require handling of this case in https://github.com/brunato/xmlschema/blob/master/xmlschema/regex.py#L235:5 and adding anchors inside each bracket if regular expression consists of numerous groups only.

**Comment by brunato** [comment]
Trying with latest version (1.0.5) `word foo` and `foo alternative` raise exceptions:

```
failed validating 'foo alternative' with XsdPatternsFacet(['(word|other)|(alternative)']):

Reason: value don't match any pattern of ['(word|other)|(alternative)'].

Schema:

  <xs:pattern xmlns:xs="http://www.w3.org/2001/XMLSchema" value="(word|other)|(alternative)" />

Instance:

  <config>foo alternative</config>

Path: /ns:data/config
```

In version 1.0.4 I've fixed a issue maybe related for that, adding an external grouping (the regex expression is ancored now with `^(` at the start and `)$` at the end instead of `^` and `$`).
Your suggestion may be non applicable. If I'm not wrong for XSD only the whole expression has to be anchored to the start and to the end of the string.

**Comment by r2dan** [comment]
@brunato it seems 1.0.5 fixes the issue. Thanks, and sorry for not checking the latest version.
